#!/usr/bin/env python3
# -*- coding: utf-8 -*-
QIWIhelp        = '/QIWIadd ключ -- добавить кошелек\n/QIWIdel -- удалить кошелек\n'
QIWIwalList     = 'Сейчас есть такие кошельки:\n'
QIWIadded       = 'Кошелек {} был добавлен\n'
QIWIwrongtoken  = 'Упс! Ключ не был найден!'
infohelp        = '/infonow -- информация о незавершенных транзакциях.\n/infohist кол-во строк -- история транзакций.\n /infomemb имя\id -- краткая информация о пользователе (id, имя, nickname)\n'
QIWIaddhelp     = '/QIWIadd ключ \nпример:\n/QIWIadd abc02qwerty89d5ef9g20poiutu62jpo\n'
QIWIdelhelp     = 'Выберите из списка элемент, который хотите удалить:'
QIWIdeleted     = 'Кошелек {} был успешно удален.'
LBTChelp        = '/LBTC hmac-key hmac-secret (заменяет существующий ключ на новый)'
LBTCadded       = 'LocalBitcoins ключ успешно добавлен'
comhelp         = '/com число(в BTC)\n  Меняет коммисию BTC\nСейчас комиссия = {} BTC'
comadded        = 'Новая комиссия - {} btc'
techhelp        = '/tech список имен через пробел (Никнеймы техподдержки. Не забудьте поменять в описании бота (@BotFather) имена)\nСейчас техподдержка: {}\n'
techadded       = 'Данные успешно добавлены\n'
infohelp        = '/infonow (без доп. параметров) показывает список текущих, еще не завершенных сделок\n/infohist кол-во строк (показывает n последних операций. Если оставить пустым, покажет 10 последних операций)\n/infomemb @username/username/userID/first name (показывает ID nickname и имя зарегистрированного пользователя, или, что такового нету в базе)\n'
infonowhelp     = 'Сейчас проходят такие операции:\nID пользователя ||| BTC кошелек ||| QIWI кошелек-получатель\n'
infohisthelp    = 'Первая операция в списке ниже - последняя из истории\nID пользователя || BTC кошелек || сумма BTC || QIWI кошелек-получатель || статус\n\n'
infomembhelp    = '/infomemb @username/username/userID/first name (показывает ID nickname и имя зарегистрированного пользователя, или, что такового нету в базе)\nпримеры /infomem PhoelixFelicitas\n/infomem @PhoelixFelicitas\n/infomem 398923487\n'
